ORGANIZATION_TYPE_LIST = [
     ['', ''],
     ['Government','10'],
     ['Other Public Sector','15'],
     ['International NGO','21'],
     ['National NGO','22'],
     ['Regional NGO','23'],
     ['Public Private Partnership','30'],
     ['Multilateral','40'],
     ['Foundation','60'],
     ['Private Sector','70'],
     ['Academic Training and Research','80']
    ]

TRANSACTION_TYPE_LIST = [
    ['Commitment', 'C'],
    ['Disbursement', 'D'],
    ['Expenditure', 'E'],
    ['Incoming Funds', 'IF'],
		['Interest Repayment', 'IR'],
    ['Loan Repayment', 'LR'],
    ['Reimbursement', 'R']
   ]

COLLABORATION_TYPE_LIST = [
   ['', ''],
   ['Aid through NGOs', 5],
   ['Aid to NGOs', 6],
   ['Aid through PPPs', 7]
  ]

AID_TYPE_LIST = [
     ['', ''],
     ['General budget support','A01'],
     ['Sector budget support','A02'],
     ['Core support to NGOs, other private bodies, PPPs and research institutes','B01'],
     ['Core contributions to multilateral institutions','B02'],
     ['Contributions to specific-purpose programmes and funds managed by international organisations','B03'],
     ['Basket funds/pooled funding','B04'],
     ['Project-type interventions','C01'],
     ['Donor country personnel','D01'],
     ['Other technical assistance','D02'],
     ['Scholarships/training in donor country','E01'],
     ['Imputed student costs','E02'],
     ['Debt relief','F01'],
     ['Administrative costs not included elsewhere','G01'],
     ['Development awareness','H01'],
     ['Refugees in donor countries','H02']
    ]

TIED_STATUS_LIST = [
     ['', ''],
     ['Partially tied', 3],
     ['Tied', 4],
     ['Untied', 5]
    ]


FLOW_TYPE_LIST = [
     ['', ''],
     ['Official development assistance (ODA)','10'],
     ['Other official flows (OOF)','20'],
     ['PRIVATE NGO','30'],
     ['PRIVATE MARKET','35']
    ]

FINANCE_TYPE_LIST = [
     ['', '']	,
     ['Aid grant excluding debt reorganisation','110'],
     ['Subsidies to national private investors','111'],
     ['Interest subsidy grant in AF','210'],
     ['Interest subsidy to national private exporters','211'],
     ['Deposit basis','310'],
     ['Encashment basis','311'],
     ['Aid loan excluding debt reorganisation','410'],
     ['Investment-related loan to developing countries','411'],
     ['Loan in a joint venture with the recipient','412'],
     ['Loan to national private investor','413'],
     ['Loan to national private exporter','414'],
     ['Non-banks guaranteed export credits','451'],
     ['Non-banks non-guaranteed portions of guaranteed export credits','452'],
     ['Bank export credits','453'],
     ['Acquisition of equity as part of a joint venture with the recipient','510'],
     ['Acquisition of equity not part of joint venture in developing countries','511'],
     ['Other acquisition of equity','512'],
     ['Debt forgiveness: ODA claims (P)','610'],
     ['Debt forgiveness: ODA claims (I)','611'],
     ['Debt forgiveness: OOF claims (P)','612'],
     ['Debt forgiveness: OOF claims (I)','613'],
     ['Debt forgiveness: Private claims (P)','614'],
     ['Debt forgiveness: Private claims (I)','615'],
     ['Debt forgiveness: OOF claims (DSR)','616'],
     ['Debt forgiveness: Private claims (DSR)','617'],
     ['Debt forgiveness: Other','618'],
     ['Debt rescheduling: ODA claims (P)','620'],
     ['Debt rescheduling: ODA claims (I)','621'],
     ['Debt rescheduling: OOF claims (P)','622'],
     ['Debt rescheduling: OOF claims (I)','623'],
     ['Debt rescheduling: Private claims (P)','624'],
     ['Debt rescheduling: Private claims (I)','625'],
     ['Debt rescheduling: OOF claims (DSR)','626'],
     ['Debt rescheduling: Private claims (DSR)','627'],
     ['Unicode Encode Error','630'],
     ['Unicode Encode Error','631'],
     ['Unicode Encode Error','632'],
     ['Foreign direct investment','710'],
     ['Other foreign direct investment, including reinvested earnings','711'],
     ['Bank bonds','810'],
     ['Non-bank bonds','811'],
     ['Other bank securities/claims','910'],
     ['Other non-bank securities/claims','911'],
     ['Securities and other instruments issued by multilateral agencies','912']
    ]

CURRENCY_LIST = [
     ['',''],
     ['Afghani','AFN'],
     ['UAE Dirham','AED'],
     ['Lek','ALL'],
     ['Armenian Dram','AMD'],
     ['Netherlands Antillian Guilder','ANG'],
     ['Kwanza','AOA'],
     ['Argentine Peso','ARS'],
     ['Australian Dollar','AUD'],
     ['Aruban Guilder','AWG'],
     ['Azerbaijanian Manat','AZN'],
     ['Convertible Marks','BAM'],
     ['Barbados Dollar','BBD'],
     ['Taka','BDT'],
     ['Bulgarian Lev','BGN'],
     ['Bahraini Dinar','BHD'],
     ['Burundi Franc','BIF'],
     ['Bermudian Dollar','BMD'],
     ['Brunei Dollar','BND'],
     ['Boliviano','BOB'],
     ['Mvdol','BOV'],
     ['Brazilian Real','BRL'],
     ['Bahamian Dollar','BSD'],
     ['Ngultrum','BTN'],
     ['Pula','BWP'],
     ['Belarussian Ruble','BYR'],
     ['Belize Dollar','BZD'],
     ['Canadian Dollar','CAD'],
     ['Congolese Franc','CDF'],
     ['Swiss Franc','CHF'],
     ['Unidades de fomento','CLF'],
     ['Chilean Peso','CLP'],
     ['Yuan Renminbi','CNY'],
     ['Colombian Peso','COP'],
     ['Unidad de Valor Real','COU'],
     ['Costa Rican Colon','CRC'],
     ['Peso Convertible','CUC'],
     ['Cuban Peso','CUP'],
     ['Cape Verde Escudo','CVE'],
     ['Czech Koruna','CZK'],
     ['Djibouti Franc','DJF'],
     ['Danish Krone','DKK'],
     ['Dominican Peso','DOP'],
     ['Algerian Dinar','DZD'],
     ['Kroon','EEK'],
     ['Egyptian Pound','EGP'],
     ['Nakfa','ERN'],
     ['Ethiopian Birr','ETB'],
     ['Euro','EUR'],
     ['Fiji Dollar','FJD'],
     ['Falkland Islands Pound','FKP'],
     ['Pound Sterling','GBP'],
     ['Lari','GEL'],
     ['Cedi','GHS'],
     ['Gibraltar Pound','GIP'],
     ['Dalasi','GMD'],
     ['Guinea Franc','GNF'],
     ['Quetzal','GTQ'],
     ['Guyana Dollar','GYD'],
     ['Hong Kong Dollar','HKD'],
     ['Lempira','HNL'],
     ['Croatian Kuna','HRK'],
     ['Gourde','HTG'],
     ['Forint','HUF'],
     ['Rupiah','IDR'],
     ['New Israeli Sheqel','ILS'],
     ['Indian Rupee','INR'],
     ['Iraqi Dinar','IQD'],
     ['Iranian Rial','IRR'],
     ['Iceland Krona','ISK'],
     ['Jamaican Dollar','JMD'],
     ['Jordanian Dinar','JOD'],
     ['Yen','JPY'],
     ['Kenyan Shilling','KES'],
     ['Som','KGS'],
     ['Riel','KHR'],
     ['Comoro Franc','KMF'],
     ['North Korean Won','KPW'],
     ['Won','KRW'],
     ['Kuwaiti Dinar','KWD'],
     ['Cayman Islands Dollar','KYD'],
 		 ['Tenge','KZT'],
 		 ['Kip','LAK'],
 		 ['Lebanese Pound','LBP'],
 		 ['Sri Lanka Rupee','LKR'],
 		 ['Liberian Dollar','LRD'],
 		 ['Loti','LSL'],
 		 ['Lithuanian Litas','LTL'],
 		 ['Latvian Lats','LVL'],
 		 ['Libyan Dinar','LYD'],
 		 ['Moroccan Dirham','MAD'],
 		 ['Moldovan Leu','MDL'],
 		 ['Malagasy Ariary','MGA'],
 		 ['Denar','MKD'],
 		 ['Kyat','MMK'],
 		 ['Tugrik','MNT'],
 		 ['Pataca','MOP'],
 		 ['Ouguiya','MRO'],
 		 ['Mauritius Rupee','MUR'],
 		 ['Rufiyaa','MVR'],
 		 ['Malawi Kwacha','MWK'],
 		 ['Mexican Peso','MXN'],
 		 ['Mexican Unidad de Inversion (UDI)','MXV'],
 		 ['Malaysian Ringgit','MYR'],
 		 ['Metical','MZN'],
 		 ['Namibia Dollar','NAD'],
 		 ['Naira','NGN'],
 		 ['Cordoba Oro','NIO'],
 		 ['Norwegian Krone','NOK'],
 		 ['Nepalese Rupee','NPR'],
 		 ['New Zealand Dollar','NZD'],
 		 ['Rial Omani','OMR'],
 		 ['Balboa','PAB'],
 		 ['Nuevo Sol','PEN'],
 		 ['Kina','PGK'],
 		 ['Philippine Peso','PHP'],
 		 ['Pakistan Rupee','PKR'],
 		 ['Zloty','PLN'],
 		 ['Guarani','PYG'],
 		 ['Qatari Rial','QAR'],
 		 ['New Leu','RON'],
 		 ['Serbian Dinar','RSD'],
 		 ['Russian Ruble','RUB'],
 		 ['Rwanda Franc','RWF'],
 		 ['Saudi Riyal','SAR'],
 		 ['Solomon Islands Dollar','SBD'],
 		 ['Seychelles Rupee','SCR'],
 		 ['Sudanese Pound','SDG'],
 		 ['Swedish Krona','SEK'],
 		 ['Singapore Dollar','SGD'],
 		 ['Saint Helena Pound','SHP'],
 		 ['Leone','SLL'],
 		 ['Somali Shilling','SOS'],
 		 ['Surinam Dollar','SRD'],
 		 ['Dobra','STD'],
 		 ['El Salvador Colon','SVC'],
 		 ['Syrian Pound','SYP'],
 		 ['Lilangeni','SZL'],
 		 ['Baht','THB'],
 		 ['Somoni','TJS'],
 		 ['Manat','TMT'],
 		 ['Tunisian Dinar','TND'],
 		 ['Paanga','TOP'],
 		 ['Turkish Lira','TRY'],
 		 ['Trinidad and Tobago Dollar','TTD'],
 		 ['New Taiwan Dollar','TWD'],
 		 ['Tanzanian Shilling','TZS'],
 		 ['Hryvnia','UAH'],
 		 ['Uganda Shilling','UGX'],
 		 ['US Dollar','USD'],
 		 ['US Dollar (Next day)','USN'],
 		 ['US Dollar (Same day)','USS'],
 		 ['Uruguay Peso en Unidades Indexadas','UYI'],
 		 ['Peso Uruguayo','UYU'],
 		 ['Uzbekistan Sum','UZS'],
 		 ['Bolivar Fuerte','VEF'],
 		 ['Dong','VND'],
 		 ['Vatu','VUV'],
 		 ['Tala','WST'],
 		 ['CFA Franc BEAC','XAF'],
 		 ['East Caribbean Dollar','XCD'],
 		 ['CFA Franc BCEAO','XOF'],
 		 ['CFP Franc','XPF'],
 		 ['Yemeni Rial','YER'],
 		 ['Rand','ZAR'],
 		 ['Zambian Kwacha','ZMK'],
 		 ['Zimbabwe Dollar','ZWL']
 	  ]

COUNTRY_LIST = [
     ['', ''],
     ['AFGHANISTAN', 'AF'],
     ['ALAND ISLANDS', 'AX'],
     ['ALBANIA', 'AL'],
     ['ALGERIA', 'DZ'],
     ['AMERICAN SAMOA', 'AS'],
     ['ANDORRA', 'AD'],
     ['ANGOLA', 'AO'],
     ['ANGUILLA', 'AI'],
     ['ANTARCTICA', 'AQ'],
     ['ANTIGUA AND BARBUDA', 'AG'],
     ['ARGENTINA', 'AR'],
     ['ARMENIA', 'AM'],
     ['ARUBA', 'AW'],
     ['AUSTRALIA', 'AU'],
     ['AUSTRIA', 'AT'],
     ['AZERBAIJAN', 'AZ'],
     ['BAHAMAS', 'BS'],
     ['BAHRAIN', 'BH'],
     ['BANGLADESH', 'BD'],
     ['BARBADOS', 'BB'],
     ['BELARUS', 'BY'],
     ['BELGIUM', 'BE'],
     ['BELIZE', 'BZ'],
     ['BENIN', 'BJ'],
     ['BERMUDA', 'BM'],
     ['BHUTAN', 'BT'],
     ['BOLIVIA, PLURINATIONAL STATE OF', 'BO'],
     ['BONAIRE, SAINT EUSTATIUS AND SABA', 'BQ'],
     ['BOSNIA AND HERZEGOVINA', 'BA'],
     ['BOTSWANA', 'BW'],
     ['BOUVET ISLAND', 'BV'],
     ['BRAZIL', 'BR'],
     ['BRITISH INDIAN OCEAN TERRITORY', 'IO'],
     ['BRUNEI DARUSSALAM', 'BN'],
     ['BULGARIA', 'BG'],
     ['BURKINA FASO', 'BF'],
     ['BURUNDI', 'BI'],
     ['CAMBODIA', 'KH'],
     ['CAMEROON', 'CM'],
     ['CANADA', 'CA'],
     ['CAPE VERDE', 'CV'],
     ['CAYMAN ISLANDS', 'KY'],
     ['CENTRAL AFRICAN REPUBLIC', 'CF'],
     ['CHAD', 'TD'],
     ['CHILE', 'CL'],
     ['CHINA', 'CN'],
     ['CHRISTMAS ISLAND', 'CX'],
     ['COCOS (KEELING) ISLANDS', 'CC'],
     ['COLOMBIA', 'CO'],
     ['COMOROS', 'KM'],
     ['CONGO', 'CG'],
     ['CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'CD'],
     ['COOK ISLANDS', 'CK'],
     ['COSTA RICA', 'CR'],
     ['COTE D\'IVOIRE', 'CI'],
     ['CROATIA', 'HR'],
     ['CUBA', 'CU'],
     ['CURACAO', 'CW'],
     ['CYPRUS', 'CY'],
     ['CZECH REPUBLIC', 'CZ'],
     ['DENMARK', 'DK'],
     ['DJIBOUTI', 'DJ'],
     ['DOMINICA', 'DM'],
     ['DOMINICAN REPUBLIC', 'DO'],
     ['ECUADOR', 'EC'],
     ['EGYPT', 'EG'],
     ['EL SALVADOR', 'SV'],
     ['EQUATORIAL GUINEA', 'GQ'],
     ['ERITREA', 'ER'],
     ['ESTONIA', 'EE'],
     ['ETHIOPIA', 'ET'],
     ['FALKLAND ISLANDS (MALVINAS)', 'FK'],
     ['FAROE ISLANDS', 'FO'],
     ['FIJI', 'FJ'],
     ['FINLAND', 'FI'],
     ['FRANCE', 'FR'],
     ['FRENCH GUIANA', 'GF'],
     ['FRENCH POLYNESIA', 'PF'],
     ['FRENCH SOUTHERN TERRITORIES', 'TF'],
     ['GABON', 'GA'],
     ['GAMBIA', 'GM'],
     ['GEORGIA', 'GE'],
     ['GERMANY', 'DE'],
     ['GHANA', 'GH'],
     ['GIBRALTAR', 'GI'],
     ['GREECE', 'GR'],
     ['GREENLAND', 'GL'],
     ['GRENADA', 'GD'],
     ['GUADELOUPE', 'GP'],
     ['GUAM', 'GU'],
     ['GUATEMALA', 'GT'],
     ['GUERNSEY', 'GG'],
     ['GUINEA', 'GN'],
     ['GUINEA-BISSAU', 'GW'],
     ['GUYANA', 'GY'],
     ['HAITI', 'HT'],
     ['HEARD ISLAND AND MCDONALD ISLANDS', 'HM'],
     ['HOLY SEE (VATICAN CITY STATE)', 'VA'],
     ['HONDURAS', 'HN'],
     ['HONG KONG', 'HK'],
     ['HUNGARY', 'HU'],
     ['ICELAND', 'IS'],
     ['INDIA', 'IN'],
     ['INDONESIA', 'ID'],
     ['IRAN, ISLAMIC REPUBLIC OF', 'IR'],
     ['IRAQ', 'IQ'],
     ['IRELAND', 'IE'],
     ['ISLE OF MAN', 'IM'],
     ['ISRAEL', 'IL'],
     ['ITALY', 'IT'],
     ['JAMAICA', 'JM'],
     ['JAPAN', 'JP'],
     ['JERSEY', 'JE'],
     ['JORDAN', 'JO'],
     ['KAZAKHSTAN', 'KZ'],
     ['KENYA', 'KE'],
     ['KIRIBATI', 'KI'],
     ['KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF', 'KP'],
     ['KOREA, REPUBLIC OF', 'KR'],
     ['KUWAIT', 'KW'],
     ['KYRGYZSTAN', 'KG'],
     ['LAO PEOPLE\'S DEMOCRATIC REPUBLIC', 'LA'],
     ['LATVIA', 'LV'],
     ['LEBANON', 'LB'],
     ['LESOTHO', 'LS'],
     ['LIBERIA', 'LR'],
     ['LIBYAN ARAB JAMAHIRIYA', 'LY'],
     ['LIECHTENSTEIN', 'LI'],
     ['LITHUANIA', 'LT'],
     ['LUXEMBOURG', 'LU'],
     ['MACAO', 'MO'],
     ['MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'MK'],
     ['MADAGASCAR', 'MG'],
     ['MALAWI', 'MW'],
     ['MALAYSIA', 'MY'],
     ['MALDIVES', 'MV'],
     ['MALI', 'ML'],
     ['MALTA', 'MT'],
     ['MARSHALL ISLANDS', 'MH'],
     ['MARTINIQUE', 'MQ'],
     ['MAURITANIA', 'MR'],
     ['MAURITIUS', 'MU'],
     ['MAYOTTE', 'YT'],
     ['MEXICO', 'MX'],
     ['MICRONESIA, FEDERATED STATES OF', 'FM'],
     ['MOLDOVA, REPUBLIC OF', 'MD'],
     ['MONACO', 'MC'],
     ['MONGOLIA', 'MN'],
     ['MONTENEGRO', 'ME'],
     ['MONTSERRAT', 'MS'],
     ['MOROCCO', 'MA'],
     ['MOZAMBIQUE', 'MZ'],
     ['MYANMAR', 'MM'],
     ['NAMIBIA', 'NA'],
     ['NAURU', 'NR'],
     ['NEPAL', 'NP'],
     ['NETHERLANDS', 'NL'],
     ['NEW CALEDONIA', 'NC'],
     ['NEW ZEALAND', 'NZ'],
     ['NICARAGUA', 'NI'],
     ['NIGER', 'NE'],
     ['NIGERIA', 'NG'],
     ['NIUE', 'NU'],
     ['NORFOLK ISLAND', 'NF'],
     ['NORTHERN MARIANA ISLANDS', 'MP'],
     ['NORWAY', 'NO'],
     ['OMAN', 'OM'],
     ['PAKISTAN', 'PK'],
     ['PALAU', 'PW'],
     ['PALESTINIAN TERRITORY, OCCUPIED', 'PS'],
     ['PANAMA', 'PA'],
     ['PAPUA NEW GUINEA', 'PG'],
     ['PARAGUAY', 'PY'],
     ['PERU', 'PE'],
     ['PHILIPPINES', 'PH'],
     ['PITCAIRN', 'PN'],
     ['POLAND', 'PL'],
     ['PORTUGAL', 'PT'],
     ['PUERTO RICO', 'PR'],
     ['QATAR', 'QA'],
     ['REUNION', 'RE'],
     ['ROMANIA', 'RO'],
     ['RUSSIAN FEDERATION', 'RU'],
     ['RWANDA', 'RW'],
     ['SAINT BARTHELEMY', 'BL'],
     ['SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA', 'SH'],
     ['SAINT KITTS AND NEVIS', 'KN'],
     ['SAINT LUCIA', 'LC'],
     ['SAINT MARTIN (FRENCH PART)', 'MF'],
     ['SAINT PIERRE AND MIQUELON', 'PM'],
     ['SAINT VINCENT AND THE GRENADINES', 'VC'],
     ['SAMOA', 'WS'],
     ['SAN MARINO', 'SM'],
     ['SAO TOME AND PRINCIPE', 'ST'],
     ['SAUDI ARABIA', 'SA'],
     ['SENEGAL', 'SN'],
     ['SERBIA', 'RS'],
     ['SEYCHELLES', 'SC'],
     ['SIERRA LEONE', 'SL'],
     ['SINGAPORE', 'SG'],
     ['SINT MAARTEN (DUTCH PART)', 'SX'],
     ['SLOVAKIA', 'SK'],
     ['SLOVENIA', 'SI'],
     ['SOLOMON ISLANDS', 'SB'],
     ['SOMALIA', 'SO'],
     ['SOUTH AFRICA', 'ZA'],
     ['SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'GS'],
     ['SPAIN', 'ES'],
     ['SRI LANKA', 'LK'],
     ['SUDAN', 'SD'],
     ['SURINAME', 'SR'],
     ['SVALBARD AND JAN MAYEN', 'SJ'],
     ['SWAZILAND', 'SZ'],
     ['SWEDEN', 'SE'],
     ['SWITZERLAND', 'CH'],
     ['SYRIAN ARAB REPUBLIC', 'SY'],
     ['TAIWAN, PROVINCE OF CHINA', 'TW'],
     ['TAJIKISTAN', 'TJ'],
     ['TANZANIA, UNITED REPUBLIC OF', 'TZ'],
     ['THAILAND', 'TH'],
     ['TIMOR-LESTE', 'TL'],
     ['TOGO', 'TG'],
     ['TOKELAU', 'TK'],
     ['TONGA', 'TO'],
     ['TRINIDAD AND TOBAGO', 'TT'],
     ['TUNISIA', 'TN'],
     ['TURKEY', 'TR'],
     ['TURKMENISTAN', 'TM'],
     ['TURKS AND CAICOS ISLANDS', 'TC'],
     ['TUVALU', 'TV'],
     ['UGANDA', 'UG'],
     ['UKRAINE', 'UA'],
     ['UNITED ARAB EMIRATES', 'AE'],
     ['UNITED KINGDOM', 'GB'],
     ['UNITED STATES', 'US'],
     ['UNITED STATES MINOR OUTLYING ISLANDS', 'UM'],
     ['URUGUAY', 'UY'],
     ['UZBEKISTAN', 'UZ'],
     ['VANUATU', 'VU'],
     ['VENEZUELA, BOLIVARIAN REPUBLIC OF', 'VE'],
     ['VIET NAM', 'VN'],
     ['VIRGIN ISLANDS, BRITISH', 'VG'],
     ['VIRGIN ISLANDS, U.S.', 'VI'],
     ['WALLIS AND FUTUNA', 'WF'],
     ['WESTERN SAHARA', 'EH'],
     ['YEMEN', 'YE'],
     ['ZAMBIA', 'ZM'],
     ['ZIMBABWE', 'ZW']
    ]

SECTORS_LIST = [
      ['Action relating to debt',	'175'],
      ['Administrative costs',	'187'],
      ['Advanced technical and managerial training',	'10'],
      ['Agrarian reform',	'102'],
      ['Agricultural alternative development',	'103'],
      ['Agricultural co-operatives',	'110'],
      ['Agricultural development',	'95'],
      ['Agricultural education/training',	'105'],
      ['Agricultural extension',	'104'],
      ['Agricultural financial services',	'109'],
      ['Agricultural inputs',	'98'],
      ['Agricultural land resources',	'96'],
      ['Agricultural policy and administrative management',	'94'],
      ['Agricultural research',	'106'],
      ['Agricultural services',	'107'],
      ['Agricultural water resources',	'97'],
      ['Agro-industries',	'127'],
      ['Air transport',	'63'],
      ['Basic drinking water supply and basic sanitation',	'31'],
      ['Basic health care',	'15'],
      ['Basic health infrastructure',	'16'],
      ['Basic life skills for youth and adults',	'5'],
      ['Basic metal industries',	'135'],
      ['Basic nutrition',	'17'],
      ['Bio-diversity',	'160'],
      ['Biomass',	'84'],
      ['Biosphere protection',	'159'],
      ['Business support services and institutions',	'92'],
      ['Cement/lime/plaster',	'132'],
      ['Chemicals',	'130'],
      ['Child soldiers (Prevention and demobilisation)',	'49'],
      ['Civilian peace-building, conflict prevention and resolution',	'45'],
      ['Coal',	'142'],
      ['Coal-fired power plants',	'77'],
      ['Communications policy and administrative management',	'66'],
      ['Construction policy and administrative management',	'150'],
      ['Cottage industries and handicraft',	'126'],
      ['Culture and recreation',	'55'],
      ['Debt buy-back',	'181'],
      ['Debt for development swap',	'179'],
      ['Debt forgiveness',	'176'],
      ['Disaster prevention and preparedness',	'186'],
      ['Early childhood education',	'6'],
      ['Economic and development policy/planning',	'35'],
      ['Education and training in transport and storage',	'65'],
      ['Education and training in water supply and sanitation',	'34'],
      ['Education facilities and training',	'1'],
      ['Education/training in banking and financial services',	'91'],
      ['Educational research',	'3'],
      ['Elections',	'40'],
      ['Electrical transmission/ distribution',	'73'],
      ['Emergency food aid',	'183'],
      ['Employment policy and administrative management',	'51'],
      ['Energy education/training',	'85'],
      ['Energy manufacturing',	'133'],
      ['Energy policy and administrative management',	'70'],
      ['Energy research',	'86'],
      ['Engineering',	'137'],
      ['Environmental education/ training',	'163'],
      ['Environmental policy and administrative management',	'158'],
      ['Environmental research',	'164'],
      ['Family planning',	'25'],
      ['Ferrous metals',	'144'],
      ['Fertilizer minerals',	'148'],
      ['Fertilizer plants',	'131'],
      ['Financial policy and administrative management',	'87'],
      ['Fishery development',	'119'],
      ['Fishery education/training',	'120'],
      ['Fishery research',	'121'],
      ['Fishery services',	'122'],
      ['Fishing policy and administrative management',	'118'],
      ['Flood prevention/control',	'162'],
      ['Food aid/Food security programmes',	'172'],
      ['Food crop production',	'99'],
      ['Forest industries',	'128'],
      ['Forestry development',	'113'],
      ['Forestry education/training',	'115'],
      ['Forestry policy and administrative management',	'112'],
      ['Forestry research',	'116'],
      ['Forestry services',	'117'],
      ['Formal sector financial intermediaries',	'89'],
      ['Free flow of information',	'42'],
      ['Fuelwood/charcoal',	'114'],
      ['Gas distribution',	'74'],
      ['Gas-fired power plants',	'76'],
      ['General budget support',	'171'],
      ['Geothermal energy',	'80'],
      ['Government administration',	'38'],
      ['Health education',	'19'],
      ['Health personnel development',	'22'],
      ['Health policy and administrative management',	'11'],
      ['Higher education',	'9'],
      ['Housing policy and administrative management',	'52'],
      ['Human rights',	'41'],
      ['Hydro-electric power plants',	'79'],
      ['Import support (capital goods)',	'173'],
      ['Import support (commodities)',	'174'],
      ['Industrial crops/export crops',	'100'],
      ['Industrial development',	'124'],
      ['Industrial minerals',	'147'],
      ['Industrial policy and administrative management',	'123'],
      ['Infectious disease control',	'18'],
      ['Informal/semi-formal financial intermediaries',	'90'],
      ['Information and communication technology (ICT)',	'69'],
      ['Land mine clearance',	'48'],
      ['Legal and judicial development',	'37'],
      ['Livestock',	'101'],
      ['Livestock/veterinary services',	'111'],
      ['Low-cost housing',	'53'],
      ['Malaria control',	'20'],
      ['Material relief assistance and services',	'182'],
      ['Medical education/training',	'12'],
      ['Medical research',	'13'],
      ['Medical services',	'14'],
      ['Mineral prospection and exploration',	'141'],
      ['Mineral/mining policy and administrative management',	'140'],
      ['Monetary institutions',	'88'],
      ['Multilateral trade negotiations',	'154'],
      ['Multisector aid for basic social services',	'54'],
      ['Multisector aid',	'165'],
      ['Multisector education/training',	'169'],
      ['Narcotics control',	'57'],
      ['Non-agricultural alternative development',	'168'],
      ['Non-ferrous metal industries',	'136'],
      ['Nonferrous metals',	'145'],
      ['Nuclear power plants',	'78'],
      ['Ocean power',	'83'],
      ['Offshore minerals',	'149'],
      ['Oil and gas',	'143'],
      ['Oil-fired power plants',	'75'],
      ['Other debt swap',	'180'],
      ['Personnel development for population and reproductive health',	'27'],
      ['Pharmaceutical production',	'134'],
      ['Plant and post-harvest protection and pest control',	'108'],
      ['Population policy and administrative management',	'23'],
      ['Post-conflict peace-building (UN)',	'46'],
      ['Power generation/non-renewable sources',	'71'],
      ['Power generation/renewable sources',	'72'],
      ['Precious metals/materials',	'146'],
      ['Primary education',	'4'],
      ['Privatisation',	'93'],
      ['Promotion of development awareness',	'193'],
      ['Public sector financial management',	'36'],
      ['Radio/television/print media',	'68'],
      ['Rail transport',	'61'],
      ['Reconstruction relief and rehabilitation',	'185'],
      ['Refugees in donor countries',	'191'],
      ['Regional trade agreements (RTAs)',	'153'],
      ['Reintegration and SALW control',	'47'],
      ['Relief co-ordination; protection and support services',	'184'],
      ['Relief of multilateral debt',	'177'],
      ['Reproductive health care',	'24'],
      ['Rescheduling and refinancing',	'178'],
      ['Research/scientific institutions',	'170'],
      ['River development',	'32'],
      ['Road transport',	'60'],
      ['Rural development',	'167'],
      ['STD control including HIV/AIDS',	'26'],
      ['Secondary education',	'7'],
      ['Sectors not specified',	'192'],
      ['Security system management and reform',	'44'],
      ['Site preservation',	'161'],
      ['Small and medium-sized enterprises (SME) development',	'125'],
      ['Social mitigation of HIV/AIDS',	'58'],
      ['Social/ welfare services',	'50'],
      ['Solar energy',	'81'],
      ['Statistical capacity building',	'56'],
      ['Storage',	'64'],
      ['Strengthening civil society',	'39'],
      ['Support to international NGOs',	'189'],
      ['Support to local and regional NGOs',	'190'],
      ['Support to national NGOs',	'188'],
      ['Teacher training',	'2'],
      ['Technological research and development',	'139'],
      ['Telecommunications',	'67'],
      ['Textiles, leather and substitutes',	'129'],
      ['Tourism policy and administrative management',	'157'],
      ['Trade education/training',	'156'],
      ['Trade facilitation',	'152'],
      ['Trade policy and administrative management',	'151'],
      ['Trade-related adjustment',	'155'],
      ['Transport equipment industry',	'138'],
      ['Transport policy and administrative management',	'59'],
      ['Tuberculosis control',	'21'],
      ['Urban development and management',	'166'],
      ['Vocational training',	'8'],
      ['Waste management/disposal',	'33'],
      ['Water resources policy and administrative management',	'28'],
      ['Water resources protection',	'29'],
      ['Water supply and sanitation - large systems',	'30'],
      ['Water transport',	'62'],
      ['Wind power',	'82'],
      ['Womens equality organisations and institutions',	'43']
    ]
