development:
  host: https://ruth.cartodb.com
  oauth_key: WbcQRDsNTBHvb0Cha8unDemZ2AoLqHXXjpEnxvq6
  oauth_secret: yDgRuV030vA30rCZUlgYwa8IWCFyLjTgPxtbFIYd
  username: ruthdelcampo@gmail.com
  password: delcampo00