development:
  host: https://whs.cartodb.com
  oauth_key: Yu6NoImrTU9jCyvDrR0SYfURbIvyLvZEu7gXisED
  oauth_secret: bgntchDURNj5kYZFVfwbZrdnpXLTZZDrPvQ45f8E
  username: whs@cartodb.com
  password: vizzualejo